
[server]
# Whether to run background indexing of the project every time
# a source document is saved.
index_on_save = true

[parse.extend_directives.grid]
argument = true
options = true
content = true
parse_content = true
content_required = true

[parse.extend_directives.grid-item-card]
argument = false
options = true
content = true
parse_content = true
content_required = true

[parse.extend_directives.uml]
argument = true
options = true
content = true
parse_content = false
content_required = false
